FROM node:current-buster-slim as base

# ---- compile image -----------------------------------------------
FROM base AS compile-image

RUN apt-get -qy update && apt-get -qy install openssl

# A wildcard is used to ensure both package.json AND package-lock.json are copied
WORKDIR /
COPY yarn.lock ./
COPY package.json ./
COPY tsconfig.json ./
COPY tsconfig.prod.json ./
COPY ./src/server/server.ts /src/server/server.ts

# Install app dependencies
RUN yarn install
RUN yarn prisma generate

CMD ["yarn", "serve:server"]