version: '3.8'

networks:
  bil-network:
    driver: bridge

volumes:
  pgsql-data:

services:
  pgsql:
    image: postgres
    restart: unless-stopped
    container_name: pgsql
    ports:
    - "5432:5432"
    env_file:
      - .env
    volumes:
      - type: volume
        source: pgsql-data
        target: /var/lib/postgresql/data
    networks:
      - bil-network

  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pgsql
    volumes:
      - type: bind
        source: ./prisma
        target: /prisma
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./static
        target: /static
    networks:
      - bil-network
