-- CreateTable
CREATE TABLE "Occurrence" (
    "id" TEXT NOT NULL,
    "OccId" TEXT NOT NULL,
    "Term" TEXT NOT NULL,
    "Scientific_Name" TEXT NOT NULL,
    "File" TEXT NOT NULL,
    "FrameId" INTEGER NOT NULL,
    "Sentence" TEXT NOT NULL,

    CONSTRAINT "Occurrence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Author" (
    "id" TEXT NOT NULL,
    "Author_y" TEXT,
    "workId" TEXT,
    "RframeMean" DOUBLE PRECISION,
    "NframeMean" DOUBLE PRECISION,
    "HframeMean" DOUBLE PRECISION,
    "SframeMean" DOUBLE PRECISION,
    "Rwork" DOUBLE PRECISION,
    "Nwork" DOUBLE PRECISION,
    "Hwork" DOUBLE PRECISION,
    "Swork" DOUBLE PRECISION,
    "Rbeta" DOUBLE PRECISION,
    "Hbeta" DOUBLE PRECISION,
    "Sbeta" DOUBLE PRECISION,
    "Author_x" TEXT,
    "RframeMean_genDiv" DOUBLE PRECISION,
    "Rwork_genDiv" DOUBLE PRECISION,
    "NframeMean_genDiv" DOUBLE PRECISION,
    "Nwork_genDiv" DOUBLE PRECISION,
    "vocab" INTEGER,
    "words" INTEGER,
    "Rbeta_genDiv" DOUBLE PRECISION,
    "Nbeta_genDiv" DOUBLE PRECISION,
    "Lustrum" INTEGER,
    "Title" TEXT,
    "Work" TEXT,
    "Age_Publication" INTEGER,
    "Year" INTEGER,
    "join" INTEGER,
    "split" INTEGER,
    "Region_x" TEXT,
    "Original_Language" TEXT,
    "Literature_Form" TEXT,
    "Genre_x" TEXT,
    "Origin" TEXT,
    "Main_Subject" TEXT,
    "Narrative_Location" TEXT,
    "Downloads" INTEGER,
    "Size" INTEGER,
    "completeFlag_x" INTEGER,
    "Literary_period_x" TEXT,
    "Literature_Form_v2" TEXT,
    "Author" TEXT,
    "Forename" TEXT,
    "Surname" TEXT,
    "Birth" INTEGER,
    "Death" INTEGER,
    "Work_Start" INTEGER,
    "Gender" TEXT,
    "Religion" TEXT,
    "Ethnicity" TEXT,
    "Native_language" TEXT,
    "Childhood_Residence" TEXT,
    "Childhood_Region" TEXT,
    "Residence" TEXT,
    "Region_y" TEXT,
    "Literary_period_y" TEXT,
    "Partners" INTEGER,
    "Children" INTEGER,
    "Highest_Education" TEXT,
    "Biodiversity_Specification" INTEGER,
    "Field" TEXT,
    "Occupation" TEXT,
    "Country" TEXT,
    "Genre_y" TEXT,
    "Works" TEXT[],
    "WorkCount" INTEGER,
    "VocabCount" INTEGER,
    "WordCount" INTEGER,
    "Birthname" TEXT,
    "Pseudonym" TEXT,
    "Aliases" TEXT,
    "Father" TEXT,
    "Mother" TEXT,
    "Languages" TEXT,
    "Employer" TEXT,
    "Position" TEXT,
    "University" TEXT,
    "Academic_Degree" TEXT,
    "Member" TEXT,
    "Death_Manner" TEXT,
    "Death_Cause" TEXT,
    "completeFlag_y" INTEGER,
    "Age" INTEGER,
    "Siblings" INTEGER,
    "Social_status" TEXT,
    "Main_Region" TEXT,
    "Main_Region_v2" TEXT,
    "Locality" INTEGER,
    "Main_Residence" TEXT,

    CONSTRAINT "Author_pkey" PRIMARY KEY ("id")
);
