-- CreateTable
CREATE TABLE "Author" (
    "id" SERIAL NOT NULL,
    "fileId" TEXT NOT NULL,
    "works" TEXT[],
    "author" TEXT,
    "forename" TEXT,
    "surname" TEXT,
    "birth" INTEGER,
    "death" INTEGER,
    "workStart" INTEGER,
    "gender" TEXT,
    "religion" TEXT,
    "ethnicity" TEXT,
    "nativeLanguage" TEXT,
    "childhoodResidence" TEXT,
    "childhoodRegion" TEXT,
    "residence" TEXT,
    "regionY" TEXT,
    "literaryPeriodY" TEXT,
    "partners" INTEGER,
    "children" INTEGER,
    "highestEducation" TEXT,
    "biodiversitySpecification" INTEGER,
    "field" TEXT,
    "occupation" TEXT,
    "country" TEXT,
    "genreY" TEXT,
    "workCount" INTEGER,
    "vocabCount" INTEGER,
    "wordCount" INTEGER,
    "birthname" TEXT,
    "pseudonym" TEXT,
    "aliases" TEXT,
    "father" TEXT,
    "mother" TEXT,
    "languages" TEXT,
    "employer" TEXT,
    "position" TEXT,
    "university" TEXT,
    "academicDegree" TEXT,
    "member" TEXT,
    "deathManner" TEXT,
    "deathCause" TEXT,
    "completeFlagY" INTEGER,
    "age" INTEGER,
    "siblings" INTEGER,
    "socialStatus" TEXT,
    "mainRegion" TEXT,
    "mainRegionV2" TEXT,
    "locality" INTEGER,
    "mainResidence" TEXT,

    CONSTRAINT "Author_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Work" (
    "fileId" TEXT NOT NULL,
    "authorY" TEXT,
    "authorX" TEXT,
    "rFrameMean" DOUBLE PRECISION,
    "nFrameMean" DOUBLE PRECISION,
    "hFrameMean" DOUBLE PRECISION,
    "sFrameMean" DOUBLE PRECISION,
    "rWork" DOUBLE PRECISION,
    "nWork" DOUBLE PRECISION,
    "hWork" DOUBLE PRECISION,
    "sWork" DOUBLE PRECISION,
    "rBeta" DOUBLE PRECISION,
    "hBeta" DOUBLE PRECISION,
    "sBeta" DOUBLE PRECISION,
    "rFrameMean_genDiv" DOUBLE PRECISION,
    "rWork_genDiv" DOUBLE PRECISION,
    "nFrameMean_genDiv" DOUBLE PRECISION,
    "nWork_genDiv" DOUBLE PRECISION,
    "vocab" INTEGER,
    "words" INTEGER,
    "rBeta_genDiv" DOUBLE PRECISION,
    "nBeta_genDiv" DOUBLE PRECISION,
    "lustrum" INTEGER,
    "title" TEXT,
    "work" TEXT,
    "agePublication" INTEGER,
    "year" INTEGER,
    "join" INTEGER,
    "split" INTEGER,
    "regionX" TEXT,
    "originalLanguage" TEXT,
    "literatureForm" TEXT,
    "genreX" TEXT,
    "origin" TEXT,
    "mainSubject" TEXT,
    "narrativeLocation" TEXT,
    "downloads" INTEGER,
    "size" INTEGER,
    "completeFlagX" INTEGER,
    "literaryPeriodX" TEXT,
    "literatureFormV2" TEXT,

    CONSTRAINT "Work_pkey" PRIMARY KEY ("fileId")
);

-- CreateTable
CREATE TABLE "Occurrence" (
    "id" INTEGER NOT NULL,
    "occId" TEXT,
    "term" TEXT,
    "scientificName" TEXT,
    "fileId" TEXT,
    "frameId" INTEGER,
    "sentence" TEXT,
    "column" INTEGER,
    "spalte" INTEGER,

    CONSTRAINT "Occurrence_pkey" PRIMARY KEY ("id")
);
